# --- quarkus ---
quarkus.banner.enabled=false

# --- auth ---
quarkus.http.auth.permission.health.paths=/q/*
quarkus.http.auth.permission.health.policy=permit
quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=authenticated

# --- n8n provider client ---
quarkus.rest-client.n8n.url=${N8N_URL:http://n8n:5678}

# --- production defaults ---
%prod.quarkus.oidc-client.client-id=${quarkus.application.name}

# --- auth disabled for dev ---
%dev.quarkus.http.auth.permission.default.policy=permit
%dev.quarkus.http.auth.proactive=false
%dev.onecx.permissions.allow-all=true
%dev.quarkus.otel.sdk.disabled=true
%dev.quarkus.oidc-client.discovery-enabled=false
%dev.tkit.security.auth.enabled=false

# --- test settings ---
%test.quarkus.test.integration-test-profile=test
%test.quarkus.otel.sdk.disabled=true
