# --- quarkus ---
quarkus.banner.enabled=false

# --- auth ---
quarkus.http.auth.permission.health.paths=/q/*
quarkus.http.auth.permission.health.policy=permit
quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=authenticated

# --- multitenancy / rest context ---
quarkus.hibernate-orm.multitenant=DISCRIMINATOR
tkit.rs.context.tenant-id.enabled=true
tkit.rs.context.token.header-param=apm-principal-token

# --- auth disabled for dev ---
%dev.quarkus.http.auth.permission.default.policy=permit
%dev.quarkus.http.auth.proactive=false
%dev.onecx.permissions.allow-all=true
%dev.quarkus.otel.sdk.disabled=true
%dev.quarkus.oidc-client.discovery-enabled=false
%dev.tkit.security.auth.enabled=false
%dev.tkit.rs.context.tenant-id.mock.enabled=false
%dev.tkit.rs.context.tenant-id.enabled=false

# --- test settings ---
%test.quarkus.test.integration-test-profile=test
%test.tkit.rs.context.token.header-param=apm-principal-token
%test.tkit.rs.context.tenant-id.mock.enabled=true
%test.tkit.rs.context.tenant-id.mock.claim-org-id=orgId
%test.tkit.rs.context.tenant-id.mock.default-tenant=default
%test.tkit.rs.context.tenant-id.mock.data.org1=org1
%test.quarkus.otel.sdk.disabled=true
%test.onecx.tenant.service.client.url=http://localhost:8089

# --- n8n provider client ---
onecx.ht.adapter.n8n.base-url=${N8N_URL:http://localhost:5678}
%test.onecx.ht.adapter.n8n.base-url=${quarkus.mockserver.endpoint}

# Required by Quarkus to create the REST client
quarkus.rest-client.n8n.url=${onecx.ht.adapter.n8n.base-url}
quarkus.rest-client.n8n.connect-timeout=10000
quarkus.rest-client.n8n.read-timeout=60000
%test.quarkus.rest-client.n8n.connect-timeout=5000
%test.quarkus.rest-client.n8n.read-timeout=10000

# --- port for dev ---
# %dev.quarkus.http.port=8085
